### ISSUE TITLE
Update to Cake.Issues 0.9.0

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues.DupFinder#26]
Update to build against Cake.Issues 0.9.0

**Comment by pascalberger** [comment]
@janniksam There's a beta version of Cake.Issues 0.9.0 available. Do you want to update this addin to the latest version or should I take care of it?

**Comment by janniksam** [comment]
@pascalberger 
Cool. Is this already the version with the column-specification in warnings?

I will see what I can do in this week / the next couple of days.

**Comment by pascalberger** [comment]
@janniksam Yes, this is the version with support for line ranges, columns and an identifier. See [release notes](https://github.com/cake-contrib/Cake.Issues/releases/tag/0.9.0-beta.1). You can see [this PR](https://github.com/cake-contrib/Cake.Issues.GitRepository/pull/76/files) as an example what to do for update (update NuGet packages and documentation).

Afterwards you can implement support for new features (I would suggest to create individual issues for every new feature, since issues are used to create release notes).

I saw that there was never a final release for 0.8.0. Do you want to create the release or should I do this?
Also there are several dependency updates pending: https://github.com/cake-contrib/Cake.Issues.DupFinder/pulls. `Cake.Core` and `Cake.Testing` should not be updated (best practice is to build against lowest version with a compatible API). You can comment with `@dependabot ignore this minor version` to tell Depandabot to ignore this version.
