### ISSUE TITLE
Setting to make the reading process multithreaded

### ISSUE THREAD

**Issue by janniksam** [cake-contrib/Cake.Issues.DupFinder#9]
Two options:
- EnableParallelism
- LimitMaxDop

**Comment by pascalberger** [comment]
Where do you see possibilities to go into parallelism during the reading process? Also do you think about implementing it in this addin or more providing another base class for multi-threaded read operations in Cake.Issues?

**Comment by janniksam** [comment]
Don't get me wrong, I havent tested out if its actually worth the syncing, but I will give it a go.

When working with 10.000+ Issues in a single file (we have 14.000 right now), it might speed up the initial reading. I will have to investigate though, when my initial pr is merged.

**Comment by janniksam** [comment]
@pascalberger 

So, I did some testing now.

File-Stats:
- 50,000 duplicates
- 2 - 5 fragments.
Time elapsed after 10 ReadIssues-calls:
--- Without parallelism on first layer (outer foreach): **28 Seconds (average: 2.8 seconds)**
--- With parallelism on first layer (outer foreach): **18 Seconds (averaging 1.8 seconds)**

I don't think it's worth offering an option for that. 50000 issues in 2.8 seconds is still pretty slow.
But I might take a look at InspectCode aswell.
